version: '3.7'

services:

  reverse-proxy:
    build:
      context: .
    environment:
      - TARGET_SERVICE=http-echo:8080
#      - ENABLE_ACCESS_LOG=true
#      - ENABLE_BASIC_AUTH=true
#      - BASIC_AUTH_BASE64=IyB0ZXN0OnRlc3QKdGVzdDokYXByMSRidWN0akk2diRpaWkyY25ObTRsdUpNc3E4YWN2UXYuCg==
#    volumes:
#       - ./testing/passwords:/etc/secrets/htpasswd
    depends_on:
      - http-echo
    ports:
      - '8080:80'

  http-echo:
    image: gcr.io/google_containers/echoserver:1.10
